import { MagnifyingGlassIcon } from "@heroicons/react/24/solid";
import Head from "next/head";
import Header from "../components/Header";
import { Popover, Transition } from "@headlessui/react";
import {
  ChevronDownIcon,
  AdjustmentsVerticalIcon,
} from "@heroicons/react/20/solid";

import {
  ShoppingBagIcon,
  ClipboardDocumentIcon,
  HomeIcon,
  EnvelopeIcon,
  EnvelopeOpenIcon,
  FolderOpenIcon,
  FaceSmileIcon,
  ArchiveBoxIcon,
} from "@heroicons/react/24/outline";
import { Fragment, useState } from "react";
import Footer from "../components/Footer";

const solutions = [
  {
    name: "HOME",
    href: "##",
    icon: HomeIcon,
  },
  {
    name: "POSTERS",
    href: "##",
    icon: ClipboardDocumentIcon,
  },
  {
    name: "ENVELOPS",
    href: "##",
    icon: EnvelopeIcon,
  },
  {
    name: "LETTERHEADS",
    href: "##",
    icon: EnvelopeOpenIcon,
  },
  {
    name: "CANVAS PRINTS",
    href: "##",
    icon: FolderOpenIcon,
  },
  {
    name: "STICKERS & LABELS",
    href: "##",
    icon: FaceSmileIcon,
  },
  {
    name: "COFFEE MUGS",
    href: "##",
    icon: ArchiveBoxIcon,
  },
];

const products = [
  {
    id: 1,
    name: "Elegant Design of Advocate",
    price: "& 199/",
    shop_type: "Free Shipping",
    review: 4,
    star: "⭐️⭐️⭐️⭐️⭐️",
    type: "Millennial",
    src: "/image/1.png",
  },
  {
    id: 2,
    name: "Elegant Design of Advocate",
    price: "& 199/",
    shop_type: "Free Shipping",
    review: 4,
    star: "⭐️⭐️⭐️⭐️⭐️",
    type: "Millennial ",
    src: "/image/2.png",
  },

  {
    id: 3,
    name: "Elegant Design of Advocate",
    price: "& 199/",
    shop_type: "Free Shipping",
    review: 4,
    type: "Millennial",
    star: "⭐️⭐️⭐️⭐️⭐️",
    src: "/image/3.png",
  },
  {
    id: 4,
    name: "Elegant Design of Advocate",
    price: "& 199/",
    shop_type: "Free Shipping",
    review: 4,
    star: "⭐️⭐️⭐️⭐️⭐️",
    type: "Zen G",
    src: "/image/4.png",
  },
  {
    id: 5,
    name: "Elegant Design of Advocate",
    price: "& 199/",
    shop_type: "Free Shipping",
    review: 4,
    star: "⭐️⭐️⭐️⭐️⭐️",
    type: "Newly Added Designs",
    src: "/image/5.png",
  },
  {
    id: 6,
    name: "Elegant Design of Advocate",
    price: "& 199/",
    shop_type: "Free Shipping",
    review: 4,
    star: "⭐️⭐️⭐️⭐️⭐️",
    type: "Session Designs ",
    src: "/image/6.png",
  },
  {
    id: 7,
    name: "Elegant Design of Advocate",
    price: "& 199/",
    shop_type: "Free Shipping",
    review: 4,
    star: "⭐️⭐️⭐️⭐️⭐️",
    type: "High-feel Designs ",
    src: "/image/7.png",
  },
  {
    id: 8,
    name: "Elegant Design of Advocate",
    price: "& 199/",
    shop_type: "Free Shipping",
    review: 4,
    star: "⭐️⭐️⭐️⭐️⭐️",
    type: "Supreme Designs ",
    src: "/image/8.png",
  },
  {
    id: 10,
    name: "Elegant Design of Advocate",
    price: "& 199/",
    shop_type: "Free Shipping",
    review: 4,
    star: "⭐️⭐️⭐️⭐️⭐️",
    type: "High-feel Designs ",
    src: "/image/9.png",
  },
  {
    id: 9,
    name: "Elegant Design of Advocate",
    price: "& 199/",
    shop_type: "Free Shipping",
    review: 4,
    star: "⭐️⭐️⭐️⭐️⭐️",
    type: "Supreme Designs ",
    src: "/image/10.png",
  },
  {
    id: 11,
    name: "Elegant Design of Advocate",
    price: "& 199/",
    shop_type: "Free Shipping",
    review: 4,
    star: "⭐️⭐️⭐️⭐️⭐️",
    type: "High-feel Designs ",
    src: "/image/11.png",
  },
];

export default function Home() {
  const [filter, setFilter] = useState(false);
  const [filterType, setFilterType] = useState("Millennial");

  return (
    <div className=" w-full  ">
      <Head>
        <title>Printasia App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/image/Bella_Basket.webp" />
      </Head>
      <main>
        <Header />
        <div className="w-full border-b px-10 h-[60px] relative flex justify-between items-center">
          <div className="w-[300px] rounded-lg shadow-md border px-2 flex justify-center items-center ">
            <MagnifyingGlassIcon className=" w-6 h-6 mr-2" />
            <input
              placeholder="Search entire store here.."
              className=" text-sm outline-none flex-1 p-2"
              type="text"
            />
          </div>

          <div className="absolute right-40   px-4">
            <Popover className="relative right-0">
              {({ open }) => (
                <>
                  <Popover.Button
                    className={`
                ${open ? "" : "text-opacity-90"}
                group inline-flex items-center rounded-md bg-pink-700 px-3 py-2 text-base font-medium text-white hover:text-opacity-100 focus:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75`}
                  >
                    <span>Solutions</span>
                    <ChevronDownIcon
                      className={`${open ? "" : "text-opacity-70"}
                  ml-2 h-5 w-5 text-pink-300 transition duration-150 ease-in-out group-hover:text-opacity-80`}
                      aria-hidden="true"
                    />
                  </Popover.Button>
                  <Transition
                    as={Fragment}
                    enter="transition ease-out duration-200"
                    enterFrom="opacity-0 translate-y-1"
                    enterTo="opacity-100 translate-y-0"
                    leave="transition ease-in duration-150"
                    leaveFrom="opacity-100 translate-y-0"
                    leaveTo="opacity-0 translate-y-1"
                  >
                    <Popover.Panel className="absolute left-1/2 z-10 mt-3 bg-white  w-[300px] -translate-x-1/2 transform px-4 sm:px-0 lg:max-w-3xl">
                      <div className="overflow-hidden rounded-lg shadow-lg ring-1 ring-black ring-opacity-5">
                        <div className="relative grid gap-8 bg-white p-5 lg:grid-cols-1">
                          {solutions.map((item) => (
                            <a
                              key={item.name}
                              href={item.href}
                              className="-m-3 flex items-center rounded-lg p-2 transition duration-150 ease-in-out hover:bg-pink-200  focus:outline-none focus-visible:ring focus-visible:ring-orange-500 focus-visible:ring-opacity-50"
                            >
                              <div className="flex h-6 w-6 shrink-0 items-center justify-center text-pink-400 sm:h-6 sm:w-6">
                                <item.icon aria-hidden="true" />
                              </div>
                              <div className="ml-4">
                                <p className="text-sm font-medium  text-gray-900">
                                  {item.name}
                                </p>
                              </div>
                            </a>
                          ))}
                        </div>
                        <div className=" p-4">
                          <a
                            href="##"
                            className="flow-root rounded-md px-2 py-2 transition duration-150 ease-in-out hover:bg-gray-100 focus:outline-none focus-visible:ring focus-visible:ring-orange-500 focus-visible:ring-opacity-50"
                          >
                            <span className="flex items-center space-y-2 ">
                              <span className="text-sm mb-2 font-medium ">
                                Documentation
                              </span>
                            </span>
                            <button className="block shadow-xl p-2 bg-pink-500 text-sm text-white">
                              VISITING CARD DESIGNS BY PROFESSION
                            </button>
                          </a>
                        </div>
                      </div>
                    </Popover.Panel>
                  </Transition>
                </>
              )}
            </Popover>
          </div>
          <div className=" flex justify-center space-x-5 items-center">
            <div className=" flex relative justify-center items-center">
              <ShoppingBagIcon className="w-8 h-8  text-pink-500" />
              <div className="absolute -top-2 -right-2 bg-pink-600 w-4 h-4 animate-bounce  rounded-full"></div>
            </div>
            <div
              onClick={() => setFilter(!filter)}
              className=" flex relative cursor-pointer justify-center items-center"
            >
              <AdjustmentsVerticalIcon className="w-8 h-8  text-pink-500" />
            </div>
          </div>
        </div>
        <div className="my-2  ">
          {filter && (
            <div className="bg-pink-100 px-5 py-3 duration-400">
              <h1 className=" text-3xl font-thin border-b border-gray-600 pb-2">
                Filter
              </h1>
              <div className=" flex justify-between items-center mt-3">
                <p className=" text-pink-800 hover:underline cursor-pointer font-bold text-sm">
                  Millennial (30)
                </p>
                <p className=" text-pink-800 hover:underline cursor-pointer font-bold text-sm">
                  Zen G (37)
                </p>
                <p className=" text-pink-800 hover:underline cursor-pointer font-bold text-sm">
                  Supreme Designs (39)
                </p>
                <p className=" text-pink-800 hover:underline cursor-pointer font-bold text-sm">
                  High-feel Designs (33)
                </p>
                <p className=" text-pink-800 hover:underline cursor-pointer font-bold text-sm">
                  Session Designs (16)
                </p>
                <p className=" text-pink-800 hover:underline cursor-pointer font-bold text-sm">
                  Newly Added Designs (23)
                </p>
              </div>
            </div>
          )}
        </div>
        <div className="min-h-screen py-10">
          <h1 className="w-full my-5 text-center font-thin text-5xl">
            PRODUCTS
          </h1>
          <div className=" flex flex-wrap mt-4 justify-center items-center">
            {products.map((product) => (
              <div
                key={product.id}
                className="w-[300px] cursor-pointer hover:scale-105 duration-300 rounded-xl  shadow-lg m-3 p-2 justify-center flex items-center flex-col"
              >
                <img className="rounded-lg border-2" src={product.src} alt="" />
                <div className=" w-full p-2">
                  <p className="text-lg w-full font-bold">{product.name}</p>
                  <p className="text-xs font-bold">Starts at {product.price}</p>
                  <p className=" text-gray-500 text-sm font-semibold">
                    Free Shipping
                  </p>
                  <p className=" text-xs ">
                    {product.star} {product.review} review
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
        <Footer />
        <div className=" w-full flex justify-center items-center">
          <p className="font-bold text-xs p-2">
            © 2022 PrintAsia.in. All Rights Reserved.
          </p>{" "}
        </div>
      </main>
    </div>
  );
}
